### obtener todas las categorias
GET http://localhost:3000/api/categoria

### crear una nueva categoria
POST http://localhost:3000/api/categoria
Content-Type: application/json

{
  "nombre": "Terror",
  "detalle": "miedoso"
}

### Modificar una categoria (Put - recurso completo e idempotente)
PUT http://localhost:3000/api/categoria/1
Content-Type: application/json

{  
  "nombre": "Acción y Aventura",	
  "detalle": "Juegos de acción, aventura y mundo abierto"
}

### Modificar una categoria (Patch - recurso parcial) 
PATCH http://localhost:3000/api/categoria/1
Content-Type: application/json

{ 
  "detalle": "Categoria para juegos de acción y aventura"
}

### borrar una categoria 
DELETE http://localhost:3000/api/categoria/4

### peticion error
GET http://localhost:3000/api/categoria/1