### Obtener todos los juegos
GET http://localhost:3000/api/juego

### Crear un nuevo juego
POST http://localhost:3000/api/juego
Content-Type: application/json

{
  "nombre": "Minecraft",
  "detalle": "cubito maincra",
  "monto": 24.99,
  "fechaLanzamiento": "2008-12-12",
  "edadPermitida": 7,
  "compania":2,
  "categorias":[3]
}

### Modificar un juego (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/juego/2
Content-Type: application/json

{
  "nombre": "Minecraft2",
  "detalle": "triangulo maincra",
  "monto": 24.99,
  "fechaLanzamiento": 2008,
  "edadPermitida": 0
}

### Modificar un juego (PATCH - recurso parcial)
PATCH http://localhost:3000/api/juego/2
Content-Type: application/json

{
  "detalle": "cubito maincra"
}

### Borrar un juego
DELETE http://localhost:3000/api/juego/1

### Obtener un juego específico
GET http://localhost:3000/api/juego/1