### obtener todos los characters
GET http://localhost:3000/api/compania

### crear un nuevo character
POST http://localhost:3000/api/compania
Content-Type: application/json

{
  "nombre": "Riot Games",
  "detalle": "Lol juego nefasto"
}

### Modificar un character (Put - recurso completo e idempotente)
PUT http://localhost:3000/api/compania/1
Content-Type: application/json

{  
  "nombre": "EA Games",	
  "detalle": "Battlefront 3"
}

### Modificar un character (Patch - recurso parcial) 
PATCH http://localhost:3000/api/compania/1
Content-Type: application/json

{ 
  "detalle": "es buena"
}

### borrar un character 
DELETE http://localhost:3000/api/compania/1

### peticion error
GET http://localhost:3000/api/compania/1