### obtener todos los characters
GET http://localhost:3000/api/compania

### crear un nuevo character
POST http://localhost:3000/api/compania
Content-Type: application/json

{
  "nombre": "Blizzard",
  "detalle": "Ni idea, solo tiene el OW"
}

### Modificar un character (Put - recurso completo e idempotente)
PUT http://localhost:3000/api/compania/4ea2591a-81e4-4360-b938-f78dc37d71e1
Content-Type: application/json

{  
  "nombre": "EA Games",	
  "detalle": "Battlefront 3"
}

### Modificar un character (Patch - recurso parcial) 
PATCH http://localhost:3000/api/compania/fe75ebef-0448-4b4a-babc-853a2c7c9a0a
Content-Type: application/json

{ 
  "detalle": "es buena"
}

### borrar un character 
DELETE http://localhost:3000/api/compania/4ea2591a-81e4-4360-b938-f78dc37d71e1

### peticion error
GET http://localhost:3000/